### ISSUE TITLE
go客户端连接最新的3.0服务时，连接一段时间后，出现版本过低

### ISSUE THREAD

**Issue by jeek120** [vesoft-inc/nebula-go#203]
刚启动服务时一起正常，等待一天后，就会出现错误，重启服务后又正常了。刚开始以为是go客户端版本太低了（之前是3.0），后面又升级到了最新的3.1，还是有问题。

> nebula.go 代码
```go
func NewDbSession() *nebula.Session {
	session, err := pool.GetSession(nebulaOpt.Username, nebulaOpt.Password)
	if err != nil {
		panic(fmt.Sprintf("获取sesion失败, %s", err.Error()))
	}
	session.Execute("use " + nebulaOpt.Space)
	return session
}
```

```go
session := db.NewDbSession()
_s.Insert(session)
session.Release()
```

> panic
```shell
Error: 获取sesion失败, fail to authenticate, error: The version of the client sending request from "x.x.x.x":64950 is lower than v2.6.0, please update the client.
```

> go.mod
```go
require (
	github.com/vesoft-inc/nebula-go/v3 v3.1.0
	google.golang.org/protobuf v1.28.0
	gopkg.in/gomail.v2 v2.0.0-20160411212932-81ebce5c23df
	gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
)
```

> docker ps 
```shell
b46cc2ff0901   vesoft/nebula-graph-studio:v3.2.3   "./server"               13 days ago   Up 13 days                0.0.0.0:7001->7001/tcp, :::7001->7001/tcp                                                                                                                            nebula-studio_web_1
6d7aa8435117   vesoft/nebula-console:v3.0.0        "sh -c 'sleep 3 \n'"     13 days ago   Exited (0) 13 days ago                                                                                                                                                                         nebula-docker-compose_console_1
88ffa08610dd   vesoft/nebula-graphd:v3.0.1         "/usr/local/nebula/b…"   13 days ago   Up 13 days (healthy)      0.0.0.0:49178->9669/tcp, :::49178->9669/tcp, 0.0.0.0:49177->19669/tcp, :::49177->19669/tcp, 0.0.0.0:49175->19670/tcp, :::49175->19670/tcp                            nebula-docker-compose_graphd2_1
132e43918916   vesoft/nebula-graphd:v3.0.1         "/usr/local/nebula/b…"   13 days ago   Up 13 days (healthy)      0.0.0.0:49176->9669/tcp, :::49176->9669/tcp, 0.0.0.0:49174->19669/tcp, :::49174->19669/tcp, 0.0.0.0:49173->19670/tcp, :::49173->19670/tcp                            nebula-docker-compose_graphd1_1
bbeefd74a112   vesoft/nebula-graphd:v3.0.1         "/usr/local/nebula/b…"   13 days ago   Up 13 days (healthy)      0.0.0.0:9669->9669/tcp, :::9669->9669/tcp, 0.0.0.0:49172->19669/tcp, :::49172->19669/tcp, 0.0.0.0:49171->19670/tcp, :::49171->19670/tcp                              nebula-docker-compose_graphd_1
f570f61a89ef   vesoft/nebula-storaged:v3.0.1       "/usr/local/nebula/b…"   13 days ago   Up 13 days (healthy)      9777-9778/tcp, 9780/tcp, 0.0.0.0:49164->9779/tcp, :::49164->9779/tcp, 0.0.0.0:49163->19779/tcp, :::49163->19779/tcp, 0.0.0.0:49162->19780/tcp, :::49162->19780/tcp   nebula-docker-compose_storaged0_1
c46dda48a551   vesoft/nebula-storaged:v3.0.1       "/usr/local/nebula/b…"   13 days ago   Up 13 days (healthy)      9777-9778/tcp, 9780/tcp, 0.0.0.0:49170->9779/tcp, :::49170->9779/tcp, 0.0.0.0:49169->19779/tcp, :::49169->19779/tcp, 0.0.0.0:49167->19780/tcp, :::49167->19780/tcp   nebula-docker-compose_storaged1_1
caa38fdfa2b8   vesoft/nebula-storaged:v3.0.1       "/usr/local/nebula/b…"   13 days ago   Up 13 days (healthy)      9777-9778/tcp, 9780/tcp, 0.0.0.0:49168->9779/tcp, :::49168->9779/tcp, 0.0.0.0:49166->19779/tcp, :::49166->19779/tcp, 0.0.0.0:49165->19780/tcp, :::49165->19780/tcp   nebula-docker-compose_storaged2_1
2fa3f79d51c4   vesoft/nebula-metad:v3.0.1          "/usr/local/nebula/b…"   13 days ago   Up 13 days (healthy)      9560/tcp, 0.0.0.0:49161->9559/tcp, :::49161->9559/tcp, 0.0.0.0:49160->19559/tcp, :::49160->19559/tcp, 0.0.0.0:49158->19560/tcp, :::49158->19560/tcp                  nebula-docker-compose_metad0_1
1c981509fd0c   vesoft/nebula-metad:v3.0.1          "/usr/local/nebula/b…"   13 days ago   Up 13 days (healthy)      9560/tcp, 0.0.0.0:49156->9559/tcp, :::49156->9559/tcp, 0.0.0.0:49154->19559/tcp, :::49154->19559/tcp, 0.0.0.0:49153->19560/tcp, :::49153->19560/tcp                  nebula-docker-compose_metad1_1
ce6a83da43c1   vesoft/nebula-metad:v3.0.1          "/usr/local/nebula/b…"   13 days ago   Up 13 days (healthy)      9560/tcp, 0.0.0.0:49159->9559/tcp, :::49159->9559/tcp, 0.0.0.0:49157->19559/tcp, :::49157->19559/tcp, 0.0.0.0:49155->19560/tcp, :::49155->19560/tcp                  nebula-docker-compose_metad2_1
```

> 服务器部分日志

```shell
[2022/04/27 04:27:51] [application] [^[[32mINFO^[[0m] [domain.go:40,Init] ^[[32mtoken初始化完成^[[0m
[2022/04/27 04:27:51] [application] [TRACE] [bus.go:154,1] 0xc0000ac6c0(ret:0xc00000c0d0) 处理事件开始: inner[3307](&{Inner:{} current:0 interval:0})
[2022/04/27 04:27:51] [application] [^[[32mINFO^[[0m] [domain.go:42,Init] ^[[32m邮箱初始化完成^[[0m
[2022/04/27 04:27:51] [application] [^[[32mINFO^[[0m] [domain.go:44,Init] ^[[32mSession初始化完成^[[0m
[2022/04/27 04:27:51] [application] [TRACE] [bus.go:156,1] 0xc0000ac6c0(ret:0xc00000c0d0) 处理事件结束: inner[3307](&{Inner:{} current:0 interval:0})
[2022/04/27 04:28:42] [application] [TRACE] [bus.go:68,Exec] 0xc00000e030(ret:0xc00000e040) Exec事件: &{Inner:{} current:0 interval:0}
......
[2022/04/27 12:24:28] [application] [TRACE] [bus.go:156,1] 0xc0000ac6c0(ret:0xc0000a40a0) 处理事件结束: inner[3307](&{Inner:{} current:0 interval:0})
[2022/04/27 12:24:56] [application] [TRACE] [bus.go:68,Exec] 0xc00000e008(ret:0xc00000e010) Exec事件: &{Inner:{} current:0 interval:0}
[2022/04/27 12:24:56] [application] [TRACE] [bus.go:154,1] 0xc0000ac6c0(ret:0xc0000a4100) 处理事件开始: inner[3307](&{Inner:{} current:0 interval:0})
[2022/04/27 12:24:56] [application] [TRACE] [bus.go:156,1] 0xc0000ac6c0(ret:0xc0000a4100) 处理事件结束: inner[3307](&{Inner:{} current:0 interval:0})
[2022/04/27 12:25:52] [application] [TRACE] [bus.go:68,Exec] 0xc0000ac048(ret:0xc0000ac050) Exec事件: &{Inner:{} current:0 interval:0}
[2022/04/27 12:25:52] [application] [TRACE] [bus.go:154,1] 0xc0000ac6c0(ret:0xc0000a4778) 处理事件开始: inner[3307](&{Inner:{} current:0 interval:0})
[2022/04/27 12:25:52] [application] [TRACE] [bus.go:156,1] 0xc0000ac6c0(ret:0xc0000a4778) 处理事件结束: inner[3307](&{Inner:{} current:0 interval:0})
[2022/04/27 12:26:44] [application] [TRACE] [bus.go:68,Exec] 0xc0000ac058(ret:0xc0000ac060) Exec事件: &{Inner:{} current:0 interval:0}
[2022/04/27 12:26:44] [application] [TRACE] [bus.go:154,1] 0xc0000ac6c0(ret:0xc0000a4a60) 处理事件开始: inner[3307](&{Inner:{} current:0 interval:0})
[2022/04/27 12:26:44] [application] [TRACE] [bus.go:156,1] 0xc0000ac6c0(ret:0xc0000a4a60) 处理事件结束: inner[3307](&{Inner:{} current:0 interval:0})
[2022/04/27 12:27:28] [application] [TRACE] [bus.go:68,Exec] 0xc00000e008(ret:0xc00000e010) Exec事件: &{Inner:{} current:0 interval:0}
[2022/04/27 12:27:28] [application] [TRACE] [bus.go:154,1] 0xc0000ac6c0(ret:0xc00000c4d8) 处理事件开始: inner[3307](&{Inner:{} current:0 interval:0})
[2022/04/27 12:27:28] [application] [TRACE] [bus.go:156,1] 0xc0000ac6c0(ret:0xc00000c4d8) 处理事件结束: inner[3307](&{Inner:{} current:0 interval:0})
[2022/04/27 12:27:56] [application] [TRACE] [bus.go:68,Exec] 0xc00000e018(ret:0xc00000e020) Exec事件: &{Inner:{} current:0 interval:0}
[2022/04/27 12:27:56] [application] [TRACE] [bus.go:154,1] 0xc0000ac6c0(ret:0xc0000a40a0) 处理事件开始: inner[3307](&{Inner:{} current:0 interval:0})
[2022/04/27 12:27:56] [application] [^[[35mERROR^[[0m] [bus.go:148,1] ^[[35m
Error: 获取sesion失败, fail to authenticate, error: The version of the client sending request from "35.172.193.194":53092 is lower than v2.6.0, please update the client.
goroutine 21 [running]:
runtime/debug.Stack()
        C:/Users/username/sdk/go1.18/src/runtime/debug/stack.go:24 +0x65
github.com/userproject/ddd/event.(*bus).Run.func1.1.1()
        C:/Users/username/project/userproject/ddd/event/bus.go:148 +0x3d
panic({0xa55f60, 0xc0001fd320})
        C:/Users/username/sdk/go1.18/src/runtime/panic.go:838 +0x207
hello.com/jing/project/server/db.NewDbSession()
        C:/Users/username/project/userproject/project/server/db/nebula.go:82 +0x174
hello.com/jing/project/server/domain.(*platform).genSysOrder(0xc0001e0720)
        C:/Users/username/project/userproject/project/server/domain/platform_gen_order.go:61 +0x467
hello.com/jing/project/server/domain.(*platform_mgr).genSysOrder(...)
        C:/Users/username/project/userproject/project/server/domain/platform_gen_order.go:91
hello.com/jing/project/server/domain.(*platform_mgr).init.func1({0xb174a0?, 0xc000081680?}, {0xc1b798?, 0xc0002ce0b0?}, 0x32000095ed8?)
        C:/Users/username/project/userproject/project/server/domain/platform_mgr.go:40 +0x94
github.com/userproject/ddd/event.(*handler).Exec(0xc0001cf200, {0xb174a0, 0xc000081680}, {0xc1b798?, 0xc0002ce0b0?}, 0x5?)
        C:/Users/username/project/userproject/ddd/event/hander.go:135 +0x472
github.com/userproject/ddd/event.(*bus).Run.func1.1(0xc0000ac6c0, {0xb174a0, 0xc000081680})
        C:/Users/username/project/userproject/ddd/event/bus.go:155 +0x325
github.com/userproject/ddd/event.(*bus).Run.func1()
        C:/Users/username/project/userproject/ddd/event/bus.go:165 +0x34
created by github.com/userproject/ddd/event.(*bus).Run
        C:/Users/username/project/userproject/ddd/event/bus.go:142 +0xe5
^[[0m
[2022/04/27 12:28:52] [application] [TRACE] [bus.go:68,Exec] 0xc00000e008(ret:0xc00000e010) Exec事件: &{Inner:{} current:0 interval:0}
[2022/04/27 12:28:52] [application] [TRACE] [bus.go:154,1] 0xc0000ac6c0(ret:0xc0000a40a0) 处理事件开始: inner[3307](&{Inner:{} current:0 interval:0})
[2022/04/27 12:28:52] [application] [^[[35mERROR^[[0m] [bus.go:148,1] ^[[35m
Error: 获取sesion失败, fail to authenticate, error: The version of the client sending request from "35.172.193.194":53090 is lower than v2.6.0, please update the client.
goroutine 21 [running]:
runtime/debug.Stack()
        C:/Users/username/sdk/go1.18/src/runtime/debug/stack.go:24 +0x65
github.com/userproject/ddd/event.(*bus).Run.func1.1.1()
        C:/Users/username/project/userproject/ddd/event/bus.go:148 +0x3d
panic({0xa55f60, 0xc000211520})
        C:/Users/username/sdk/go1.18/src/runtime/panic.go:838 +0x207
hello.com/jing/project/server/db.NewDbSession()
        C:/Users/username/project/userproject/project/server/db/nebula.go:82 +0x174
hello.com/jing/project/server/domain.(*platform).genSysOrder(0xc0001e0720)
```

**Comment by Aiee** [comment]
Hi, this bug has been fixed in https://github.com/vesoft-inc/nebula/pull/4075. Please update the Nebula service to v3.0.2 or newer.
